version: "3"
services:
  theater_db:
    image: mongo
    container_name: theater_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwer1234
    ports:
      - 6001:27017
